[workspace]
members = ["crates/*"]

[workspace.package]
authors = ["TeamDman"]
repository = "https://github.com/TeamDman/FlowCore.git"
edition = "2024"

[workspace.dependencies]
clap = { version = "4.5.37", features = ["derive"] }
color-eyre = "0.6.3"
eyre = "0.6.12"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
ollama-rs = { version = "0.3.1", features = ["stream"] }
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = "0.1.14"

[package]
name = "FlowCore"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
color-eyre.workspace = true
eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
